### ISSUE TITLE
extract_genres_from_file_directories returning 0x80131937 aka 2148735287

### ISSUE THREAD

**Issue by jeffshumphreys** [jeffshumphreys/filmcab#41]
Probably return a 1. But more task scheduler error messages.

**Comment by jeffshumphreys** [comment]
Message from _log transcript:
**_SELECT 
     directory_path                      / What we are going to search for new files     /
  ,  useful_part
FROM 
    directories_ext_v_**
Message: Exception calling "ExecuteReader" with "0" argument(s): "ERROR [42703] ERROR: column "useful_part" does not exist;
Error while executing the query"
StackTrace:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Failed on 396
Error Record= Exception calling "ExecuteReader" with "0" argument(s): "ERROR [42703] ERROR: column "useful_part" does not exist;
Error while executing the query"
**********************
Command start time: 20240212143945
**********************
PS>TerminatingError(): "System error."

**Comment by jeffshumphreys** [comment]
Actual error # was 42703. So nothing to do with what the Task Scheduler displayed. Simplot: Who cares. Boise: Wut? VisitPay: That's not your job!!!!!!!!!!!!!

**Comment by jeffshumphreys** [comment]
Fixed. Will wait to run before clos-ed the case.

**Comment by jeffshumphreys** [comment]
Ran-ed.
